---
#initial input parameters
log_parameters:
    log_level: DEBUG
    showtiming: true
network_topology_parameters:
    supernetwork_parameters:
        title_string: trouteRunCalib
        geo_file_path: /glade/scratch/adamw/calibration_tests/11042400/domain/RouteLink.nc 
        mask_driver_string: txt
        mask_layer_string: ""
        mask_key: 0
        break_network_at_gages: true
        columns:
            key: link
            downstream: to
            dx: Length
            n: n 
            ncc: nCC  
            s0: So 
            bw: BtmWdth  
            waterbody: NHDWaterbodyComID
            tw: TopWdth  
            twcc: TopWdthCC 
            alt: alt
            musk: MusK
            musx: MusX
            cs: ChSlp 
            gages: gages
        waterbody_null_code: -9999
        terminal_code: 0
        driver_string: NetCDF
        layer_string: 0
    waterbody_parameters:
        break_network_at_waterbodies: true 
        level_pool:
            level_pool_waterbody_parameter_file_path: /glade/p/cisl/nwc/nwmv30_finals/CONUS/DOMAIN_DefaultParams/LAKEPARM_NWMv3.0.nc
            level_pool_waterbody_id: lake_id
            level_pool_waterbody_area: LkArea
            level_pool_weir_elevation: WeirE
            level_pool_waterbody_max_elevation: LkMxE
            level_pool_outfall_weir_coefficient: WeirC
            level_pool_outfall_weir_length: WeirL
            level_pool_overall_dam_length: DamL
            level_pool_orifice_elevation: OrificeE
            level_pool_orifice_coefficient: OrificeC
            level_pool_orifice_area: OrificeA
        rfc:
            reservoir_parameter_file: /glade/work/adamw/CONUS/DOMAIN/reservoir_index_AnA.nc
            reservoir_rfc_forecasts: False
            reservoir_rfc_forecasts_time_series_path: /glade/work/adamw/CONUS/rfc_timeseries
            reservoir_rfc_forecasts_lookback_hours: 48
compute_parameters:
    parallel_compute_method: by-subnetwork-jit-clustered
    compute_kernel: V02-structured
    assume_short_ts: true
    subnetwork_target_size: 100
    cpu_pool: 12
    restart_parameters:
        lite_channel_restart_file: 
        wrf_hydro_channel_restart_file:
        wrf_hydro_channel_ID_crosswalk_file: /glade/scratch/adamw/calibration_tests/11042400/domain/RouteLink.nc
        wrf_hydro_channel_ID_crosswalk_file_field_name: link
        wrf_hydro_channel_restart_upstream_flow_field_name: qlink1
        wrf_hydro_channel_restart_downstream_flow_field_name: qlink2
        wrf_hydro_channel_restart_depth_flow_field_name: hlink
        wrf_hydro_waterbody_restart_file:
        wrf_hydro_waterbody_ID_crosswalk_file: /glade/p/cisl/nwc/nwmv30_finals/CONUS/DOMAIN_DefaultParams/LAKEPARM_NWMv3.0.nc 
        wrf_hydro_waterbody_ID_crosswalk_file_field_name: lake_id
        wrf_hydro_waterbody_crosswalk_filter_file: /glade/scratch/adamw/calibration_tests/11042400/domain/RouteLink.nc
        wrf_hydro_waterbody_crosswalk_filter_file_field_name: NHDWaterbodyComID
    forcing_parameters:
        qts_subdivisions: 12
        dt: 300
        qlat_input_folder: /glade/scratch/adamw/calibration_tests/11042400/forcing/OUTPUT
        qlat_file_pattern_filter: "*CHRTOUT_DOMAIN1"
        qlat_file_index_col: feature_id
        qlat_file_value_col: q_lateral
        nts: 
        max_loop_size: 720       
output_parameters:
    lite_restart:
        lite_restart_output_directory: 
    chanobs_output:
        chanobs_output_directory:
        chanobs_filepath: CHANOBS_DOMAIN1.nc
